# Auto-assign configuration
addReviewers: true
addAssignees: true
reviewers:
  - octocat
  # Replace with actual maintainer username
numberOfReviewers: 1

assignees:
  - octocat
  # Add your team members here
numberOfAssignees: 1

skipKeywords:
  - wip
  - draft
