# Auto-labeling configuration
"type: feature":
  - "feature/**"
"type: bugfix":
  - "bugfix/**"
"type: hotfix":
  - "hotfix/**"
"type: release":
  - "release/**"
"area: frontend":
  - "app/components/**/*"
  - "app/pages/**/*"
  - "app/styles/**/*"
"area: backend":
  - "app/api/**/*"
  - "app/lib/**/*"
  - "app/server/**/*"
"area: database":
  - "app/lib/db.ts"
  - "app/migrations/**/*"
"area: docker":
  - "Dockerfile"
  - "docker-compose.yml"
  - "docker-compose.*.yml"
"area: ci/cd":
  - ".github/workflows/**/*"
